version: "3.8"

services:
  nodejs-api:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: nodejs-api
    ports:
      - "${PORT:-3000}:3000"
    environment:
      NODE_ENV: production
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    volumes:
      - ./app:/app
    command: ["node", "src/server.js"]
