version: "3.8"

services:
  nodejs-api:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: nodejs-api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./app:/app
    command: ["node", "src/server.js"]
